name: CanvasGroupy

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - python=3.10.9
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - jupyterlab
  - partd
  - nbdev
  - pip
  - pip:
    - git+https://github.com/tdimiduk/groupeng.git
    - PyGithub
    - canvasapi
