# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CanvasGroupy',
                'doc_host': 'https://FleischerResearchLab.github.io',
                'git_url': 'https://github.com/FleischerResearchLab/CanvasGroupy',
                'lib_path': 'CanvasGroupy'},
  'syms': {'CanvasGroupy.core': {'CanvasGroupy.core.foo': ('core.html#foo', 'CanvasGroupy/core.py')}}}
