# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_GroupEngAssign.ipynb.

# %% auto 0
__all__ = ['assign_groups']

# %% ../nbs/01_GroupEngAssign.ipynb 3
import GroupEng

def assign_groups(groupeng_config:str # Directory for the GroupEng config yml file
                 ) -> (bool, str): # Status and output directory of the compile file.
    status, outdir = GroupEng.run(groupeng_config)
    return status, outdir 
