project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
    contents:
      - auto: "/index.ipynb"
      - section: Tutorials
        contents: tutorials/*
      - section: API
        contents: api/*
      - section: Project Feedback Template
        contents: feedback_template/*

metadata-files: [nbdev.yml]