project:
  type: website
  output-dir: _docs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "CanvasGroupy"
  site-url: "https://FleischerResearchLab.github.io/CanvasGroupy"
  description: "Canvas Grouping Python Script"
  repo-branch: main
  repo-url: "https://github.com/FleischerResearchLab/CanvasGroupy"
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
    contents:
      - auto: "/index.ipynb"
      - section: Tutorials
        contents: tutorials/*
      - section: API
        contents: api/*
      - section: Project Feedback Template
        contents: feedback_template/*
