ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "CanvasGroupy"
  site-url: "https://FleischerResearchLab.github.io/CanvasGroupy"
  description: "Canvas Grouping Python Script"
  twitter-card: true
  open-graph: true
  repo-branch: main
  repo-url: "https://github.com/FleischerResearchLab/CanvasGroupy"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/FleischerResearchLab/CanvasGroupy"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
